language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
    - pip3 install -e .
    - pip3 install pytest black mypy

script:
    - pytest
    - black --check scalpl tests setup.py
    - mypy scalpl
