language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip3 install -e .
    - pip3 install pytest
    - pip3 install black

script:
    - pytest
    - black --check scalpl tests setup.py
